version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab.javeoff.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.javeoff.com'
        nginx['redirect_http_to_https'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
      GITLAB_SKIP_UNMIGRATED_DATA_CHECK: 'true'
    ports:
      - '445:443'
      - '82:80'
      - '2224:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    shm_size: '256m'
