services:
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    environment:
      - LOGSPOUT=ignore
      - VIRTUAL_HOST=portainer.javeoff.com
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=portainer.javeoff.com
      - LETSENCRYPT_EMAIL=javeoff@yandex.ru
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
